services:
  # 后端服务
  backend:
    image: kb_backend
    container_name: kb-backend
    env_file:
      - backend/.env
    environment:
      - PYTHONPATH=/app
    volumes:
      - backend_data:/app/data
      - backend_data:/app/uploads
      - backend_logs:/app/logs
      - ./backend/.env:/app/.env:ro
    networks:
      - kb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 前端服务
  frontend:
    image: kb_frontend
    container_name: kb-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - kb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

# 数据卷
volumes:
  backend_data:
    driver: local
  backend_logs:
    driver: local

# 网络
networks:
  kb-network:
    driver: bridge
    name: kb-upload-genie-network