services:
  # 后端服务
  backend:
    image: ghcr.io/pancrepal-xiaoyibao/kb-backend:latest
    container_name: kb-backend
    env_file:
      - backend/.env
    environment:
      - PYTHONPATH=/app
    volumes:
      - backend_data:/app/data
      - backend_uploads:/app/uploads
      - backend_logs:/app/logs
      - ./backend/.env:/app/.env:ro
    networks:
      - kb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    user: "1001:1001"  # 使用与Dockerfile中相同的用户ID
    # 添加初始化命令确保目录权限正确
    command: >
      sh -c "
        mkdir -p /app/uploads /app/logs /app/data &&
        chown -R 1001:1001 /app/uploads /app/logs /app/data &&
        chmod -R 775 /app/uploads /app/logs /app/data &&
        exec uvicorn main:app --host 0.0.0.0 --port 8002 --reload
      "

  # 前端服务
  frontend:
    image: ghcr.io/pancrepal-xiaoyibao/kb-frontend:latest
    container_name: kb-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - kb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

# 卷定义
volumes:
  backend_data:
    driver: local
  backend_uploads:
    driver: local
  backend_logs:
    driver: local

# 网络
networks:
  kb-network:
    driver: bridge
    name: kb-upload-genie-network
